### ISSUE TITLE
Show the txn input addresses 

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#111]

**Comment by Senyoret1** [comment]
Would you like to have the hash replaced by the address (as is normally done in other explorers) or would you like to have both the hash and the address (in this case it would be good to show the hash of the output as well).

**Comment by gz-c** [comment]
Can replace the hash with the txn input data (address, hours, coins etc)

**Comment by samuelvisscher** [comment]
@erichquist could you make a design suggestion for this?

**Comment by gz-c** [comment]
Do not wait for a design suggestion

**Comment by Senyoret1** [comment]
I added two related problems in Skycoin/Skycoin: https://github.com/skycoin/skycoin/issues/918 y https://github.com/skycoin/skycoin/issues/919
