### ISSUE TITLE
Make txn input hashes clickable

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#114]

**Comment by Senyoret1** [comment]
Waiting for https://github.com/skycoin/skycoin-explorer/issues/111#issuecomment-361054950. It could also be done as part of https://github.com/skycoin/skycoin-explorer/pull/107

**Comment by gz-c** [comment]
Does not require a designer or mobile responsiveness to add an href

**Comment by Senyoret1** [comment]
I added two related problems in Skycoin/Skycoin: https://github.com/skycoin/skycoin/issues/918 y https://github.com/skycoin/skycoin/issues/919 (important to obtain the address of each input efficiently )
