### ISSUE TITLE
Display block and transaction size 

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#135]
This will require API changes in skycoin core

**Comment by gz-c** [comment]
Backend issue https://github.com/skycoin/skycoin/issues/1170

**Comment by gz-c** [comment]
Transaction size is already included as "length"

**Comment by gz-c** [comment]
#1201 adds "size" to block API responses

**Comment by Senyoret1** [comment]
Solved in https://github.com/skycoin/skycoin-explorer/pull/177

**Comment by olemis** [comment]
Let's close it then
