### ISSUE TITLE
Update layout to match new sitecoin.net design

### ISSUE THREAD

**Issue by AlexSugak** [skycoin/skycoin-explorer#140]
Rewrite of [skycoin.net](https://www.skycoin.net/) to apply new design is currently in progress.
New version of the site will link skycoin-explorer, as before. 
Therefore, skycoin-explorer layout should be updated to match new design.

Things to update:
- header
- footer
- navigation
- other minor fixes (e.g. fonts)

Also see skycoin/blog#712

**Comment by gz-c** [comment]
@AlexSugak is this done?

**Comment by AlexSugak** [comment]
yes, closing
