### ISSUE TITLE
Show the amount of coinhours

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#150]
Currently, the explorer shows the amount of coins in the inputs and outputs, but not the amout of coinhours. Before making the changes, https://github.com/skycoin/skycoin/issues/918 and https://github.com/skycoin/skycoin/issues/919 must be solved, therefore, I have published this issue as a reminder to make the changes as soon as the previous conditions are met.

**Comment by Senyoret1** [comment]
On all pages? Or just on the Unspent Outputs page?

**Comment by gz-c** [comment]
Probably all pages, if the API data is there

**Comment by Senyoret1** [comment]
Ok, I just need https://github.com/skycoin/skycoin/pull/1686 to be merged to start.

**Comment by Senyoret1** [comment]
Ok, I just https://github.com/skycoin/skycoin/pull/1636 to be merged to start.

**Comment by gz-c** [comment]
The data is available now, using `verbose=1` in the query params
