### ISSUE TITLE
Unconfirmed transactions page does not load

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#154]
https://explorer.skycoin.net/app/unconfirmedtransactions
<img width="392" alt="screen shot 2018-03-26 at 9 01 53 pm" src="https://user-images.githubusercontent.com/26845312/37907869-f0d2c5fa-3138-11e8-8929-bd37ae1088db.png">

**Comment by Senyoret1** [comment]
My fault. The error only appears if there are no unconfirmed transactions. Fixed in https://github.com/skycoin/skycoin-explorer/pull/155
