### ISSUE TITLE
Problem with the responsive menu

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#162]
On a cell phone screen, the navigation menu should look like this:
![menu_](https://user-images.githubusercontent.com/34079003/38213833-ab0a3442-3690-11e8-8a8d-71d3506b4a77.png)

However, if the browser window has a height of 480px (normal in phones), it looks like this:
![menu](https://user-images.githubusercontent.com/34079003/38213892-df535436-3690-11e8-8e65-017fcbf4a964.png)

The menú was made for the website, so I suppose that it should be fixed there first.

**Comment by AlexSugak** [comment]
@Senyoret1 could you please test with latest version? should be fixed.

**Comment by Senyoret1** [comment]
Hi, I did some tests and the problem with the button was solved. While testing, I found 3 things. The first is that now there are 2 scroll bars, but only in the desktop browser. I think it would only be noticed by people using an old crt monitor or a very small browser window.

![nv](https://user-images.githubusercontent.com/34079003/38595551-83ef8d36-3d1a-11e8-8315-7155a22dbcd9.jpg)

In Firefox the button have two lines of text, probably because of the space occupied by the scroll bars.

![nv_2](https://user-images.githubusercontent.com/34079003/38595592-b8504ade-3d1a-11e8-8059-db2af389bf04.jpg)

The third point is perhaps the most evident. I tested the explorer with the latest version of Chrome on Android and it looks very good (the two scroll bars are gone, even in landscape mode), but the scroll does not work correctly. It is possible to scroll by moving the finger in the shaded area (also in the drawer menu itself, if the phone is tall enough to fit all the contents of the drawer) and the result is this:

![nv_3](https://user-images.githubusercontent.com/34079003/38595815-d0fb7cb0-3d1b-11e8-9d21-1dbb8fb145df.png)

In the image you can see how the scroll made the header to be above both the shaded area and the menu, and that the scroll bar on the right side corresponds to the content of the page and not the menu.

**Comment by AlexSugak** [comment]
@Senyoret1 thank you! will fix the header issue and look into what can be done with small monitor issues
