### ISSUE TITLE
Wrong scroll position

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#163]
When opening a link, the requested page opens, but the scroll does not return to the top, it stays where it was when the link was clicked. Likewise, if the browser's back button is pressed, the scroll stays in the same position when returning to the previous page. All this makes navigation weird.

Likewise, when paging in the block list and when an address is selected within the address screen itself (for example), the scroll remains in the same place and there are no indications that more data is being loaded.

I think that two things should be done:

- Because the explorer does not have a well defined linear navigation, but can be navigated in a circular way, there is no simple way in Angular to save the scroll position (at least I could not find a satisfactory way after about 3 hours of tests). Taking this into account, a simple solution would be to make the scroll always return to the initial when navigating between pages.

- After pressing a link that does not change the current page, but only the parameter that indicates what data to show (as in the list of blocks and the address page), the scroll should return to the beginning and the screen should be cleaned, in such a way that it is obvious that new data is being loaded.

If the two previous solutions seem appropriate, I can start to make the changes. However, any other suggestion is welcome.

**Comment by gz-c** [comment]
sounds good
