### ISSUE TITLE
Options for centralizing the texts

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#165]
Currently the explorer has many repeated texts. Placing them in a central location would help avoid future errors when making changes. TThe process could be done in different ways, including the usage of a translation library. Translating the explorer might be good, but it also could involve some complications for maintainability, so I would like to know if this would be appropriate. Taking this into account, would you prefer the texts to be centralized using a translation library?

**Comment by samuelvisscher** [comment]
It's a great idea to use a centralized language strategy

**Comment by gz-c** [comment]
Sounds good

**Comment by Senyoret1** [comment]
I have been investigating the best way to do this and it seems like the best option is to use this library: https://github.com/ngx-translate/core . It is true that Angular has native tools to handle i18n, but these have major problems and are still experimental. For example, it is not possible to change the language easily (it is even necessary to create a new build for each language if aot is enabled) and there are no ways to access the texts in the ts code (only in the templates). Even the official Ionic website recommends using ngx-translate instead of Angular's i18n options https://ionicframework.com/docs/developer-resources/ng2-translate/

Looking at all this, I would like to know if it would be ok if I add ngx-translate as a dependency.

Additionally, this could also be relevant for https://github.com/skycoin/skycoin/issues/1263 , since using the same library in all projects would facilitate the reuse of code.

**Comment by gz-c** [comment]
ngx-translate says something about angular v5 vs v6, which are we using?

**Comment by gz-c** [comment]
The library should be fine to use

**Comment by Senyoret1** [comment]
The explorer is using Angular 5. At this moment Angular 6 has not been officially launched, it is at RC state.

**Comment by Senyoret1** [comment]
Solved in https://github.com/skycoin/skycoin-explorer/pull/178
