### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#212]
The explorer's texts could be translated using ngx-translate. However, the explorer use the same header and footer as the website. I could modify them to work with ngx-translate and thus be able to translate all the content, but I don't know if I should just do it, as those controls are being maintained by another team.

Another improvement that could be added is to integrate a list of known addresses. That way, if an output or an input belongs to a known address, the name of the owner could be displayed instead of the address. That way the user could see that the transactions come not from an unknown address but from "X Exchange", for example. Other explorers do something similar.

@gz-c , what do you think about these changes?

**Comment by gz-c** [comment]
The header is not the same as skycoin.net's anymore, although the footer is the same.

We could exclude the header and footer from the translate for now.

I'll make tagging an address a separate issue. That will need some thought
