### ISSUE TITLE
Add /health endpoint

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#230]
Add /health endpoint. Returns:

- [ ] blockchain metadata
- [ ]  version data
- [ ] number of open connections
- [ ] uptime

**Comment by olemis** [comment]
@gz-c  what metrics ?

**Comment by gz-c** [comment]
It can proxy the internal node's health endpoint

**Comment by olemis** [comment]
@Senyoret1 the important thing is to get this done . @stdevHan is finishing with another issue today and I was thinking of assigning this one to him , but if you prefer to do it ; it's ok . Let me know (or assign it to yourself)

**Comment by olemis** [comment]
BTW , we need this for another ongoing work done by @stdevNorge

**Comment by Senyoret1** [comment]
Ok, I was just checking, to prevent working on something that someone else could be aready solving. I'm going to start working on this, but I can not assign myself because I do not have permissions to do that on this repository.

**Comment by olemis** [comment]
Oh , it's easy to identify the issues we are working on . They are assigned to someone and labeled with `stdev` and `wip` labels .

**Comment by Senyoret1** [comment]
👍
