### ISSUE TITLE
Slow API query for address

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#232]
See https://github.com/skycoin/skycoin/issues/1786 for details.  Explorer's side will need some coordination with whatever optimizations are necessary.

**Comment by gz-c** [comment]
Another example address:

https://explorer.skycoin.net/app/address/CyY4sqLzdZvAVT4f4dkL4YBfBSLohben3o/1

The console's network tab indicates that the API requests are finishing soon enough, but it still takes a long time to show the data on the page. This could be a frontend problem.

**Comment by Senyoret1** [comment]
The problem is that the transactions have too many outputs and Angular suffers when trying to create so many controls. The change in #247 should help make it work better
