### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin-explorer#243]
- Time should be displayed in 24h format or with AM/PM indicators to avoid confusion.
- Unnecessary timestamp is being shown on tx page 

Timestamp in the info table and in the tx header as well

![screenshot 2018-10-08 at 16 25 10](https://user-images.githubusercontent.com/1536298/46614890-3ba2a000-cb17-11e8-9120-d6ec288bd3ab.png)

Timestamp only in the info table

![screenshot 2018-10-08 at 16 25 18](https://user-images.githubusercontent.com/1536298/46614888-3ba2a000-cb17-11e8-930a-e8cbad7b9fd6.png)

**Comment by Senyoret1** [comment]
I had not noticed that #240 was already approved and I made the changes there, I'm sorry
