### ISSUE TITLE
Problems using Safari 9

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#248]
The explorer have important render problems in Safari 9. The contents are always displayed in front of the footer (red arrow) and, if the window is very narrow, the lateral menu is always displayed (without pressing the menu button) so it is not possible to view the content:
![explorer](https://user-images.githubusercontent.com/34079003/47048660-14784e00-d169-11e8-879c-7ecdaef540e8.png)
Using iOS 9 the menu problem makes it impossible to see the content.

@gz-c and @mahansky , could you check if the problem continues with recent versions of Safari?

**Comment by mahansky** [comment]
Looks good on Safari 12

![screenshot 2018-10-16 at 23 41 30](https://user-images.githubusercontent.com/1536298/47049296-2b389800-d19d-11e8-95b0-a5ecf0f3aca8.png)
![screenshot 2018-10-16 at 23 43 12](https://user-images.githubusercontent.com/1536298/47049334-486d6680-d19d-11e8-91ab-1434cbde2b0e.png)
![screenshot 2018-10-16 at 23 41 56](https://user-images.githubusercontent.com/1536298/47049297-2b389800-d19d-11e8-9656-f620c1379a2e.png)
