### ISSUE TITLE
System.import()

### ISSUE THREAD

**Issue by mahansky** [skycoin/skycoin-explorer#252]
./src/app/app.translate-loader.ts
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/

**Comment by Senyoret1** [comment]
The problem seems to be relatively complicated. Simply changing `System.import()` with `import()` does not work. In the issues 21560 and 23426 of the Angular repository even for now the discussion focuses on temporarily ignoring the warning.

**Comment by mahansky** [comment]
Oh okay, I didn't know it doesn't work with Angular 5 (works with 6 btw)
