### ISSUE TITLE
Add ability for "named" addresses

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#268]
Other explorers will display a name/tag for known addresses, such as an exchange's withdrawal address.

We are considering removing explorer.go and merging the API into the skycon node directly, there isn't a need for the explorer.go proxy any more, because we have the `-enable-api-sets` feature in Skycoin core.

In that case, this annotation data would have to be stored in the Skycoin node.  And we would need a mechanism for annotating these addresses (such as an admin control).  Initially we could load from a JSON file on disk.

This may tie into a general annotation/notes system in Skycoin core.

**Comment by Senyoret1** [comment]
@gz-c , what do you think about using a JSON file in this repository to store the data, instead of saving it in the node, at least for now?

**Comment by gz-c** [comment]
We have a notes system in the node now, so I would prefer to use that

**Comment by Senyoret1** [comment]
Hmm, I'm not sure about what would be the best approach to implement this feature using the notes system, so I'll wait for it to be defined then.

**Comment by gz-c** [comment]
You would use the `/data` endpoints (notes API) to return annotations for various types (addresses, transactions)
