### ISSUE TITLE
Use the node API directly

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#293]
Currently the explorer uses an intermediate server to obtain the data, but there isn't a need for the explorer.go proxy any more, because we have the `-enable-api-sets` feature in Skycoin core.

@gz-c, do you think there is something that should to be done before starting this change?

**Comment by gz-c** [comment]
It will change the URLs.  I was thinking of adding an explorer mode to the node, to preserve these URLs, or act as a special API set which exposes only the URLs needed for the explorer.  We'd also want to move the documentation endpoint into the node.

**Comment by Senyoret1** [comment]
For me, changing the backend URLs is not problem, but if you are talking about other people using the API, then if there is a problem.

As a temporary solution, maybe we could make the frontend connect directly to the node, but without deleting explorer.go (to keep it as a legacy API). If more features are added to the node, the UI will be able to use them without problems and users of the legacy explorer API will have a reason to migrate to the node API and, maybe, connect to any other node, instead of the one used by the explorer. However, I can not be sure about how convenient this would be, because I don't know who and how is using the API right now.

On the other hand, using the node's API would allow to easily distribute the explorer with the desktop wallet (I think I remember that was discussed a while ago). Making an special "explorer mode" for the node could make that more complicated.
