### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by Whatyes** [skycoin/skycoin-explorer#295]
I try to access the API (Skywallet runs on my local machine) from a web service that also runs on my local machine (Apache). 

`Access to XMLHttpRequest at 'http://localhost:xxxx/api/v1/coinSupply' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by gz-c** [comment]
Tell your apache server to ignore CORS?

**Comment by gz-c** [comment]
Or put nginx/apache in front and add the origin you want to cors
