### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#36]
* Add configuration option to serve TLS
* Add Let's Encrypt support for automatic certs
* Force https https://github.com/unrolled/secure

**Comment by samuelvisscher** [comment]
@gz-c Do you still want this to be executed? With the improved node setup being implemented in Skycoin Core (--disable-wallet-api) we will be able to remove explorer.go, meaning HTTPS support can come from Skycoin Core and the service that serves the html files (Apache of Nginx)

**Comment by gz-c** [comment]
Closing this, will allow the operator to add HTTPS through nginx
