### ISSUE TITLE
front-end doen't load: ngDevMode is not defined

### ISSUE THREAD

**Issue by NESS-Network** [skycoin/skycoin-explorer#360]
After build using make all, make run 
node backend ok 
Uncaught ReferenceError: ngDevMode is not defined
    zUnb https://explorer.privateness.network/main-es2015.6ffee3f81413d9110f4a.js:1
    a https://explorer.privateness.network/runtime-es2015.5dc8809facdb96c4ff44.js:1
    0 https://explorer.privateness.network/main-es2015.6ffee3f81413d9110f4a.js:1
    a https://explorer.privateness.network/runtime-es2015.5dc8809facdb96c4ff44.js:1
    t https://explorer.privateness.network/runtime-es2015.5dc8809facdb96c4ff44.js:1
    r https://explorer.privateness.network/runtime-es2015.5dc8809facdb96c4ff44.js:1
    <anonymous> https://explorer.privateness.network/main-es2015.6ffee3f81413d9110f4a.js:1

**Comment by Senyoret1** [comment]
Maybe the problem is you have to run `npm install` before being able to build the front-end: https://github.com/skycoin/skycoin-explorer#initial-configuration-steps
