### ISSUE TITLE
Show decimal places in balances

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#43]

**Comment by efosao** [comment]
@gz-c how many decimal spaces?

**Comment by gz-c** [comment]
@efosao 6

The api will either return a string like `"1.123456"` for coins,
or a number like `1123456`.  If its a number like that, format it as "1.123456"
Mostly they will look like `10000000` which would be `"10.000000"`.

**Comment by samuelvisscher** [comment]
Solved a while ago
