### ISSUE TITLE
Timestamps are incorrect

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#44]

**Comment by efosao** [comment]
is the goal to switch from UTC to local time?

```js
// ./src/app/components/pages/block-chain-table/block-chain-table.component.ts
  getTime(time){
    // return moment.unix(time).utc().format('YYYY-MM-DD HH:mm:ss'); // utc time
    return moment.unix(time).format('YYYY-MM-DD HH:mm:ss'); // local time
  }
```

**Comment by gz-c** [comment]
I'm not sure, someone reported that the timestamps were incorrect.

If they are formatted as UTC time, then add `" UTC"` to the timestamp.

I think we can keep it in UTC time but add `" UTC"` to the timestamp for now

**Comment by montycrypto** [comment]
This has been solved by using the standard Angular date format pipe
