### ISSUE TITLE
Cache coinSupply response in case skycoin node is unavailable

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#48]
/api/coinSupply updates infrequently, we should cache the last successful response and use that if the backend skycoin node in unreachable.

Recently the skycoin node crashed, which caused our rank to collapse on CMC because our circulating supply was unavailable.  Caching `/api/coinSupply` would help prevent this situation from occuring.

**Comment by montycrypto** [comment]
This should be done in the Go part I assume?

**Comment by gz-c** [comment]
Yes

**Comment by gz-c** [comment]
Not doing this
