### ISSUE TITLE
Popdown menu does not work in explorer

### ISSUE THREAD

**Issue by skycoin-manager** [skycoin/skycoin-explorer#51]
- when clicking the upper left, there should be a pop down menu with a list of options (similar to the skycoin wallet)
- one of the tabs needs to be "unconfirmed transactions" and display the unconfirmed transactions in the pool and number of seconds since the transaction was first seen

**Comment by samuelvisscher** [comment]
Not relevant anymore with redesign, unconfirmed transactions are described here:

https://github.com/skycoin/skycoin-explorer/issues/17
