### ISSUE TITLE
Overlapping text on /block page

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#56]
<img width="1182" alt="screen shot 2017-12-12 at 12 43 03 pm" src="https://user-images.githubusercontent.com/26845312/33867806-0dfafe1e-df3a-11e7-8cbd-74bea4255e19.png">

**Comment by montycrypto** [comment]
Based on the font it appears that the old style sheet was not discarded yet, can you do a hard refresh (ctrl + f5) and see if you still see this bug?

**Comment by gz-c** [comment]
i did cmd+shift+r on chrome/osx and same problem

**Comment by gz-c** [comment]
Its working now
