### ISSUE TITLE
Add timezone (or UTC) to timestamp

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#57]

**Comment by montycrypto** [comment]
Timezone should be localized based on computer settings, do you see an incorrect time? If not, should I still add UTC or timezone?

**Comment by gz-c** [comment]
They should be UTC time and add " UTC" to the timestamp to clarify that
Someone reported incorrect timestamps, I don't know if its true

**Comment by gz-c** [comment]
Related or duplicate: #44

**Comment by montycrypto** [comment]
Then we can close it, that issue has been resolved
