### ISSUE TITLE
Floating point error in balance

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#63]
<img width="237" alt="screen shot 2017-12-15 at 12 28 03 pm" src="https://user-images.githubusercontent.com/26845312/34026800-77b38834-e193-11e7-8bb1-7b547582f17e.png">

this screenshot is from https://explorer.skycoin.net/app/address/bxpUG8sCjeT6X1ES5SbD2LZrRudqiTY7wx

Need to use fixed point decimal library to do the math, or use integer math then specifically format it with 6 decimal places.

The balance should be `8343.077` (or `8343.077000`, if not truncating the finals zeroes)

**Comment by samuelvisscher** [comment]
Solved with https://github.com/skycoin/skycoin-explorer/pull/88
