### ISSUE TITLE
Balance not showing on Address Detail

### ISSUE THREAD

**Issue by montycrypto** [skycoin/skycoin-explorer#77]
https://explorer.skycoin.net/app/address/2DKzAMXpm5xynNSWwN3Q1QMJAuFAE1vEHar
https://explorer.skycoin.net/api/currentBalance?addrs=2DKzAMXpm5xynNSWwN3Q1QMJAuFAE1vEHar

Balance call returns status 500 

Possibly related to: https://github.com/skycoin/skycoin-explorer/issues/68

PS. mobile back-end does not have status 500 (older version):

http://128.199.57.221/balance?addrs=2DKzAMXpm5xynNSWwN3Q1QMJAuFAE1vEHar

**Comment by Senyoret1** [comment]
Apparently, the problem is not in the explorer code. If you use this URL, the problem is still present: http://127.0.0.1:6420/outputs?addrs=2DKzAMXpm5xynNSWwN3Q1QMJAuFAE1vEHar

**Comment by samuelvisscher** [comment]
Appears to have been resolved
