### ISSUE TITLE
Double-click to select timestamp or transaction id problem

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#81]
When double-clicking to select either the timestamp or transaction id on the address page (and others), both the transaction id and timestamp become highlighted.  This interferes with copy/pasting either value

**Comment by Senyoret1** [comment]
It can be fixed, but at this moment there are several pull request modifying those lines of code waiting for approval and I think there could be conflicts. But I'm not very good at using git, so I'm not entirely sure.

**Comment by samuelvisscher** [comment]
@gz-c This issue appears to be resolved now?

**Comment by Senyoret1** [comment]
After all the changes, it works better. However, it still does not work totally well. I'm going to do some tests to see how to improve it.
