### ISSUE TITLE
Some addresses redirect to /block when searching

### ISSUE THREAD

**Issue by gz-c** [skycoin/skycoin-explorer#83]
Searching for this address: `n3E1TTLwZcmxu3CZpbEZbUT8eX4kQgujh`
redirects to https://explorer.skycoin.net/app/block/n3E1TTLwZcmxu3CZpbEZbUT8eX4kQgujh instead of https://explorer.skycoin.net/app/address/n3E1TTLwZcmxu3CZpbEZbUT8eX4kQgujh

**Comment by Senyoret1** [comment]
Fixed in https://github.com/skycoin/skycoin-explorer/pull/80 . Before the system assumed that 34-35 characters strings were addresses, now it accepts as addresses strings with 27-34 characters.

**Comment by gz-c** [comment]
Maybe a backend endpoint should handle search. Ideally the address is checked for validity by parsing it.

@samuelvisscher do we have a skycoin address parser in javascript?

**Comment by Senyoret1** [comment]
I made some changes to try to improve the code without needing to make very deep modifications. Please, take a look at https://github.com/skycoin/skycoin-explorer/pull/80#issuecomment-356821303
