### ISSUE TITLE
Show how many coins are entering o leaving on the address details page

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skycoin-explorer#90]
https://github.com/skycoin/skycoin-explorer/pull/74 changed the address screen for showing if the coins entered or exited in a transaction. The change does not shows exactly how many coins entered or exited because it is not possible to do it in an optimal way. At this time, /api/address (explorer's api) and /explorer/address (node's api) return the amount of coins in the outputs, but not in the inputs, so it is not possible to know how many coins went out of the address.

Para que se muestre cuantas monedas entraron o salieron hay dos opciones, cada una con sus ventajas y desventajas.

To show how many coins entered or exited there are 2 options, each with its advantages and disadvantages.

**Option 1:**

/address_uxouts (api of the node) could be added to explorer.go, so that after calling /api/address to obtain all the transactions of an address /address_uxouts could be called to get all the values of all the inputs and outputs of the address. In this way, it would be possible to do the calculation.

The problem is that the client would then be making 2 calls and, taking into account that /address_uxouts returns a significant amount of data and a separate query, it would require unnecesary work from the server and more bandwidth.

If this option is used, the problems could be minimized by modifing explorer.go to remove all the not necessary data that is being returned (something that would help to improve the overall performance of the system).
 
**Option 2:**

The other option is to add the amount of coins of each input in the response of /explorer/address (in the Skycoin node). The response is currently as follows:
```
"inputs": [
    {
        "uxid": "8b64d9b058e10472b9457fd2d05a1d89cbbbd78ce1d97b16587d43379271bed1",
        "owner": "c9zyTYwgR4n89KyzknpmGaaDarUCPEs9mV"
    }
]
```
After the modification, it should look similar to the following:
```
"inputs": [
    {
        "uxid": "8b64d9b058e10472b9457fd2d05a1d89cbbbd78ce1d97b16587d43379271bed1",
        "owner": "c9zyTYwgR4n89KyzknpmGaaDarUCPEs9mV",
        "coins": "2.000000"
     }
]
```
With this change, it would be possible to calculate how many coins entered and exited during the transaction.

**Next step:** please share your opinions about which option should be used.

Small line at the end just to notify @gz-c and @samuelvisscher

**Comment by gz-c** [comment]
Option 2 seems better, will look into changing this on the skycoin/skycoin repo

**Comment by samuelvisscher** [comment]
Solved in explorer
